# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-28 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('area', models.CharField(default='', max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=45)),
                ('post_code', models.CharField(max_length=5)),
                ('borough', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ZipCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='shelter',
            name='service_area',
            field=models.ManyToManyField(to='sleepez.ZipCodes'),
        ),
    ]
