# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-28 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepez', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='area',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='service_area',
        ),
        migrations.AlterField(
            model_name='shelter',
            name='phone',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.DeleteModel(
            name='ZipCodes',
        ),
    ]
