# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-28 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepez', '0002_auto_20180428_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=200)),
                ('borough', models.CharField(max_length=45)),
                ('contact_name', models.CharField(max_length=45)),
                ('contact_phone', models.CharField(max_length=45)),
                ('contact_email', models.CharField(blank=True, max_length=45)),
            ],
        ),
        migrations.AlterField(
            model_name='shelter',
            name='post_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
