# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-29 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleepez', '0004_auto_20180428_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelter',
            old_name='Latitude',
            new_name='latitude',
        ),
    ]
